<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-04-05 12:52

$extensionPath = t3lib_extMgm::extPath('irre_tutorial');
return array(
	'tx_irretutorial_module1' => $extensionPath . 'mod1/index.php',
	'tx_irretutorial_1ncsvworkspacestest' => $extensionPath . 'tests/class.tx_irretutorial_1ncsvWorkspacesTest.php',
	'tx_irretutorial_1nffworkspacestest' => $extensionPath . 'tests/class.tx_irretutorial_1nffWorkspacesTest.php',
	'tx_irretutorial_abstract' => $extensionPath . 'tests/class.tx_irretutorial_Abstract.php',
	'tx_irretutorial_abstractlocalization' => $extensionPath . 'tests/class.tx_irretutorial_AbstractLocalization.php',
	'tx_irretutorial_abstractworkspaces' => $extensionPath . 'tests/class.tx_irretutorial_AbstractWorkspaces.php',
	'tx_irretutorial_mnmmaysmlocalizationkeeptest' => $extensionPath . 'tests/class.tx_irretutorial_mnmmaysmLocalizationKeepTest.php',
	'tx_irretutorial_mnmmaysmlocalizationselecttest' => $extensionPath . 'tests/class.tx_irretutorial_mnmmaysmLocalizationSelectTest.php',
);
?>