<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-10-10 10:53

$extensionPath = t3lib_extMgm::extPath('irre_tutorial');
return array(
	'tx_irretutorial_module1' => $extensionPath . 'mod1/index.php',
	'tx_irretutorial_1ncsvtest' => $extensionPath . 'tests/class.tx_irretutorial_1ncsvTest.php',
	'tx_irretutorial_1nfftest' => $extensionPath . 'tests/class.tx_irretutorial_1nffTest.php',
	'tx_irretutorial_abstracttest' => $extensionPath . 'tests/class.tx_irretutorial_abstractTest.php',
);
?>